# Generated by Django 5.0.3 on 2024-03-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
