# Generated by Django 5.0.3 on 2024-03-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0002_customer_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='good_for',
            field=models.IntegerField(default=1),
        ),
    ]
