# Generated by Django 5.0.3 on 2024-03-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0003_room_good_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='fee',
        ),
        migrations.AddField(
            model_name='room',
            name='fees',
            field=models.ManyToManyField(blank=True, to='room_management.fee'),
        ),
    ]
