# Generated by Django 5.0.3 on 2024-03-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0006_alter_building_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='updated_by',
        ),
    ]
