# Generated by Django 5.0.3 on 2024-03-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0007_remove_room_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
