# Generated by Django 5.0.3 on 2024-03-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0008_fee_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='remarks',
        ),
    ]
