# Generated by Django 5.0.3 on 2024-03-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0010_customer_price_at_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='plate_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
