# Generated by Django 5.0.3 on 2024-03-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0012_customer_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='check_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
