# Generated by Django 5.0.3 on 2024-03-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0013_alter_customer_check_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='extra_bed',
            field=models.IntegerField(default=0),
        ),
    ]
