# Generated by Django 5.0.3 on 2024-03-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0014_customer_extra_bed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraBedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Extra Bed Price',
                'verbose_name_plural': 'Extra Bed Prices',
            },
        ),
    ]
