# Generated by Django 5.0.3 on 2024-03-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0015_extrabedprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='check_in_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
