# Generated by Django 5.0.3 on 2024-03-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0017_customer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='extra_bed_price_at_check_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
