# Generated by Django 5.0.3 on 2024-03-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0018_customer_extra_bed_price_at_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='original_check_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
