# Generated by Django 5.0.3 on 2024-03-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='stock',
        ),
        migrations.AddField(
            model_name='purchase',
            name='stock',
            field=models.ManyToManyField(blank=True, to='inventory_management.stock'),
        ),
    ]
