# Generated by Django 5.0.3 on 2024-03-17 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_remove_purchase_stock_purchase_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='stock',
            new_name='stocks',
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.product')),
            ],
            options={
                'verbose_name': 'Barcode',
                'verbose_name_plural': 'Barcodes',
            },
        ),
    ]
