# Generated by Django 5.0.3 on 2024-03-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0003_rename_stock_purchase_stocks_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='barcodes',
            field=models.ManyToManyField(blank=True, to='inventory_management.barcode'),
        ),
    ]
