# Generated by Django 5.0.3 on 2024-03-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0004_stock_barcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='batch_no',
            field=models.IntegerField(),
        ),
    ]
