# Generated by Django 5.0.3 on 2024-03-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0005_alter_stock_batch_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='batch_no',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='expiry_date',
            field=models.DateField(blank=True),
        ),
    ]
