# Generated by Django 5.0.3 on 2024-03-18 12:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0009_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
