# Generated by Django 5.0.3 on 2024-03-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0010_alter_stock_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='identifier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
