# Generated by Django 5.0.3 on 2024-03-18 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0011_alter_stock_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='products_bought',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.CreateModel(
            name='PurchaseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_items', to='inventory_management.purchase')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.stock')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
            },
        ),
    ]
