# Generated by Django 5.0.3 on 2024-03-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0012_remove_purchase_products_bought_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseItems',
            new_name='PurchaseItem',
        ),
    ]
