# Generated by Django 5.0.3 on 2024-03-18 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0013_rename_purchaseitems_purchaseitem'),
        ('room_management', '0017_customer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room_management.customer'),
        ),
    ]
