# Generated by Django 5.0.3 on 2024-03-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0015_purchase_is_walk_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='price_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
